django-app/SER/SER/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("ser", include("homepage.urls")),
]

django-app/SER/homepage/urls.py
import imp
from operator import index
from . import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

app_name = "homepage"
urlpatterns = [
    path("", views.index, name="index"),
    path("upload", views.upload, name="upload"),
    path("nu", views.nu, name="nu"),
    path("contact", views.contact, name="contact"),
]

django-app/SER/homepage/models.py
from django.db import models

# Create your models here.
class Document(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    file = models.FileField()

django-app/SER/homepage/forms.py
from django import forms
from .models import Audio_store


class AudioForm(forms.ModelForm):
    class Meta:
        model = Audio_store
        fields = ["record"]

django-app/SER/homepage/views.py
from django.http import HttpResponse
from django.shortcuts import render
from SER.settings import BASE_DIR, MEDIA_ROOT
from homepage.models import Document
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
import os
from django.template import loader
from .sermodel.model import predict


# Create your views here.


def index(request):
    return render(request, "homepage/index.html")


def upload(request):
    if request.method == "POST":
        try:
            myfile = request.FILES["audiofile"]
        except:
            return JsonResponse("Didn't recieve any file!", safe=False)
        fs = FileSystemStorage()
        filepath = fs.save(myfile.name, myfile)
        filename = os.path.basename(filepath)
        result = predict(filepath)
        context = {
            "result": result,
        }
        return render(request, "homepage/result.html", context)

    return render(request, "homepage/nu.html")


def nu(request):
    return render(request, "homepage/nu.html")


def contact(request):
    return render(request, "homepage/contact.html")

django-app/SER/homepage/templates/homepage/ads.html
    
    <div class="main-container">
        <div class="heading">
          <h1 class="heading__title">Speech Emotion Recognition</h1>
          <p class="heading__credits">  Harness the power of Deep Learning to predict emotions!!!</p>
        </div>
        <div class = "subheading">
            <h3>Emotions which we are able to predict : </h3>
        </div>
        <div class="cards">
          <div class="card card-1">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
            <h2 class="card__title">Neutral :| </h2>
          </div>

          <div class="card card-2">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
           <h2 class="card__title">Happy :)</h2>

          </div>

          <div class="card card-3">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
           <h2 class="card__title">Sad :(</h2>
          </div>

          <div class="card card-4">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
           <h2 class="card__title">Angry :<</h2>
            
          </div>


          <div class="card card-5">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
           <h2 class="card__title">Disgust</h2>
          
          </div>

          <div class="card card-1">
            <div class="card__icon"><i class="fas fa-bolt"></i></div>
            <p class="card__exit"><i class="fas fa-times"></i></p>
         
            <h2 class="card__title">Fear</h2>
          </div>

        </div>

django-app/SER/homepage/templates/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel = "stylesheet" href = "{% static 'homepage/style.css'%}">
</head>
<body>

    <nav>
        <a href="{% url 'homepage:index' %}">Home</a>
        <a href="{% url 'homepage:upload' %}">Predict</a>
        <a href="#">About</a>
        <a href="{% url 'homepage:contact' %}">Contact</a>
        <a href="#">Help</a>
        <div class="animation start-home"></div>
    </nav>
    <img src="{% static 'homepage/img/logo1.png'%}" class = "logo" />
    {% block body %}
    {% endblock %}
    
</body>
</html>

django-app/SER/homepage/templates/homepage/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "stylesheet" href = "{% static 'homepage/s3.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Edu+VIC+WA+NT+Beginner&family=Noto+Sans:wght@600;800&family=Poppins:wght@300&display=swap" rel="stylesheet">
    <title>Contact</title>
</head>
<body>
    <nav>
        <a href="{% url 'homepage:index' %}">Home</a>
        <a href="{% url 'homepage:upload' %}">Predict</a>
        <a href="#">About</a>
        <a href="{% url 'homepage:contact' %}">Contact</a>
        <a href="#">Help</a>
        <div class="animation start-home"></div>
    </nav>
    <div id="collection">
        <div class="card">
            <img class="image" src = "{% static 'homepage/img/sammy.jpeg'%}" alt="Avatar">
            <div class = "title">Sameer Mishra</div>
            <div class = "content">
                Expert @ Codeforces | Knight @ LeetCode | Ex-Technical Coordinator @ RPH | Full Stack Developer | JIIT'23 ||<br>
                <a href="https://www.linkedin.com/in/sameer-mishra-68b34b194/">Linkedin : Sameer Mishra</a>        
                 </div>
            <div class = "profession">Software Developer Engineer Intern At Inframarket</div>
            <div class="social">
                
            </div>
        </div>
        <div class="card">
            <img class="image" src = "{% static 'homepage/img/sushi.jpeg'%}"alt="Avatar">
            <div class = "title">Sushant Kumar</div>
            <div class = "content">
                Knight @ Leetcode | Specialist @ Codeforces | Profecient in Core Java | Django Developer ||
                <a href="https://www.linkedin.com/in/sushant-kumar-41b7721a0/">Linkedin : Sushant Kumar</a></div>
                
            <div class = "profession">Upcoming Specialist Programmer At Infosys</div>
            <div class="social">
                
            </div>
        </div>
        <div class="card">
            <img class="image" src = "{% static 'homepage/img/yas.jpeg'%}" alt="Avatar">
            <div class = "title">Yash Jalan</div>
            <div class = "content"> 
                Full Stack Developer | JIIT'23 ||
                <a href="https://www.linkedin.com/in/yash-jalan-a54b62230/">Linkedin : Yash Jalan</a>
            </div>
            <div class = "profession">Software Developer Engineer Intern At Evalueserve</div>
            <div class="social">
                
            </div>
        </div>
    </div>
</body>
</html>

django-app/SER/homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}
{% load static %}
<html>
    <head>
        <title>
            SER APP
        </title>
        <link rel = "stylesheet" href = "{% static 'homepage/style.css'%}">
    </head>
    <body>
        {% block body %}
        
    <div class="main-container">
        <div class="heading">
          <h1 class="heading__title">Speech Emotion Recognition</h1>
          <p class="heading__credits">  Harness the power of Deep Learning to predict human emotions.</p>
        </div>
        <div class = "subheading">
            <h3>Emotions which we are able to predict : <br> </h3>
        </div>
        
        
        <section class="grid">
          <div cass = "imgs" >
            <img src= "{% static 'homepage/img/neutral.jpg'%}" alt="Sample photo">
            <div class="neut">Neutral</div>  
          </div>

          <div cass = "imgs" >
            <img src= "{% static 'homepage/img/happy.jpg'%}" alt="Sample photo">
            <div class="happyt">Happy</div>  
          </div>

          <div cass = "imgs" >
            <img src= "{% static 'homepage/img/sad.jpg'%}" alt="Sample photo">
            <div class="sadt">Sad</div>  
          </div>

          <div cass = "imgs" >
            <img src= "{% static 'homepage/img/angry.jpg'%}" alt="Sample photo">
            <div class="angryt">Angry</div>  
          </div>

          <div cass = "imgs" >
            <img src= "{% static 'homepage/img/scared.jpg'%}" alt="Sample photo">
            <div class="feart">Fear</div>  
          </div>
          
          <div cass = "imgs" >
            <img src= "{% static 'homepage/img/disgust.jpg'%}" alt="Sample photo">
            <div class="disgust">Disgust</div>  
          </div>
        </section>
        
    </div>
        
    <div class="footer">
      <h3>   SER by Sameer Mishra, Sushant Kumar and Yash Jalan. Batch'19-23 JIIT.</h3>
    </div>
        {% endblock %}
    </body>
</html>

django-app/SER/homepage/templates/homepage/nu.html
{% load static %}
<head>
    <link rel = "stylesheet" href = "{% static 'homepage/s2.css'%}">
</head>
<body>
    <nav>
        <a href="{% url 'homepage:index' %}">Home</a>
        <a href="{% url 'homepage:upload' %}">Predict</a>
        <a href="#">About</a>
        <a href="">Contact</a>
        <a href="#">Help</a>
        <div class="animation start-home"></div>
    </nav>
    <div class="login-box">
        <h2>Upload your Audio File</h2>
        <img src = "{% static 'homepage/img/waves.gif'%}">  
        <div class="form">
            <form method= "POST" enctype="multipart/form-data">
                {%csrf_token %}
                <div class="file-input">
                    <label for="file">   
                    </label>
                    <input type="file" id="file" name="audiofile">
                    <div class="selected-file"></div>
                </div>
                <button class="submit-btn" type="Upload">Submit and Predict</button>
            </form>
        </div>
    </div>
    
</body>

django-app/SER/homepage/templates/homepage/result.html
{% load static %}
<html>
<head>
<title>Result
    
</title>
<link rel = "stylesheet" href = "{% static 'homepage/s2.css'%}">
</head>
<body>
    
    <nav>
        <a href="{% url 'homepage:index' %}">Home</a>
        <a href="{% url 'homepage:upload' %}">Predict</a>
        <a href="#">About</a>
        <a href="{% url 'homepage:contact' %}">Contact</a>
        <a href="#">Help</a>
        <div class="animation start-home"></div>
    </nav>


<div class="login-box">
    <h2 style="font-size: 30px;">Results</h2>
    <img src = "{% static 'homepage/img/waves.gif'%}">  
    

    <h2>The emotion predicted is : {{result}}</h2>
    
</div>
</body>
</html>